### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Himanshu-Vishwas**
I have reviewed the documentation for the GitHub Source in Vanus and here are my observations:

The introduction section provides a clear explanation of what the GitHub Source does and how it converts GitHub webhook events into CloudEvents.

The Quick Start section is well written and easy to understand. It provides all the necessary information to set up the GitHub Source, including prerequisites and the creation of the config file.

The table in the config file section clearly explains the different options available in the config file.

The documentation has no grammar errors, and capitalization is correct. All the links in the documentation are working except the payload image link.

Overall, the documentation is well-written and easy to understand. The steps to set up and use the GitHub Source are clearly explained.

**Changes:**
-

### CODE REVIEW

**Comment by JieDing** [comment]
@Himanshu-Vishwas Thanks so much for your review of this Documentation. Can you also help us to run this connector ? Just to make sure developers can run the connector successfully by following our doc.

**Comment by Himanshu-Vishwas** [comment]
sure!

**Comment by Michaelg22** [comment]
hi, @Himanshu-Vishwas have you encountered any issues?

**Comment by Himanshu-Vishwas** [comment]
No.

**Pull request closed without merging**
